exact_match: src.eval.metrics.exact_match.ExactMatch
semantic_similarity: src.eval.metrics.semantic_similarity.SemanticSimilarity
lexical_overlap: src.eval.metrics.lexical_overlap.LexicalOverlap
faithfulness: src.eval.metrics.faithfulness.Faithfulness
#robustness: src.eval.metrics.robustness.RobustnessByDegree