# === EMBEDDING & INDEX SETTINGS ===

# Modèle de représentation
# configs/embed/settings.yaml.yaml
raw_dir: data/raw
index_dir: index
embedding_model: sentence-transformers/all-MiniLM-L6-v2
text_field: context
embedding_batch_size: 64
chunk_size: 400
chunk_overlap: 65
top_k: 3
alpha: 0.5
use_gpu: false
parquet_path: data/raw/squad_train.parquet